-- TQ9 app production deployment execution note
-- Status: executed on Hostinger on 2026-06-20 after the pre-account DB replay.
-- This is an evidence note only. Do not source this file.
--
-- Target:
-- - App URL: https://app.toquran.org
-- - Hostinger user/home: u504065335 / /home/u504065335
-- - App path:
--   /home/u504065335/domains/toquran.org/public_html/appdashboard
-- - Production DB: u504065335_to_quran
-- - PHP runtime used for app commands: /opt/alt/php83/usr/bin/php (8.3.31)
-- - Composer path: /usr/local/bin/composer
--
-- Secret handling:
-- - SSH, DB, mail, app key, generated account passwords, and reset tokens are
--   not recorded here.
-- - The production .env was written directly on Hostinger with mode 600.
-- - Because temporary SSH/DB credentials were shared during deployment prep,
--   rotate them after website smoke and launch handoff complete.
--
-- Code/package:
-- - Source commit packaged: 2fe1b2dbaf22
-- - Local archive name:
--   toquranapp-deploy-2fe1b2dbaf22-20260620-182346.tgz
-- - Archive size: 175,295,382 bytes
-- - Remote archive:
--   /home/u504065335/toquranapp-deploy-2fe1b2dbaf22-20260620-182346.tgz
-- - Package scan excluded .env, .git, Composer vendor, node_modules, docs,
--   tests, database/manual, raw SQL, and backups.
-- - Package included built assets, app runtime files, public assets, and
--   Library/storage content. The required catalog source file
--   to_quran_adhkar_dua_banks.md was uploaded after the first catalog dry-run
--   reported it missing.
--
-- App install:
-- - composer install --no-dev --optimize-autoloader completed.
-- - composer check-platform-reqs --no-dev passed on PHP 8.3.31.
-- - artisan optimize:clear completed.
-- - artisan config:cache completed.
-- - artisan view:cache completed.
-- - artisan route:cache completed.
-- - public/storage was corrected from a copied directory to the Laravel
--   storage symlink, and root .htaccess rewrites /storage/* to public storage
--   files only when the public file exists.
-- - Visual login smoke then showed the inherited Week14/KL root logo/favicon
--   because Hostinger serves this subdomain from the project root. Root
--   .htaccess was updated to rewrite public asset URLs for /assets, /images,
--   /pwa, and /build into public/ when the public file exists, preserving the
--   private-source deny rules while making asset() resolve to the To Quran
--   public logo/favicon.
--
-- Production .env safe summary:
-- - APP_ENV=production
-- - APP_DEBUG=false
-- - APP_URL=https://app.toquran.org
-- - APP_KEY present
-- - DB target present for u504065335_to_quran
-- - MAIL_* present, with support mailbox identity present
-- - TOQURAN_DEFAULT_TEACHER_EMAIL=drosamaqandil@gmail.com
-- - SESSION_DRIVER=database
-- - QUEUE_CONNECTION=database
-- - CACHE_STORE=database
-- - FILESYSTEM_DISK=local
--
-- Account bootstrap:
-- - Created two launch users only:
--   - owner superadmin (active, super_admin role)
--   - default teacher drosamaqandil@gmail.com (active, teacher role)
-- - Generated one-time passwords were not printed or committed.
-- - A password reset email was sent for the owner superadmin account; mailer
--   returned passwords.sent and one password_reset_tokens row exists.
--
-- Post-account SQL:
-- - Ran database/manual/patches/
--   2026-06-07-tq6-library-folder-mode-and-quran-repetition-import.sql
-- - Ran database/manual/patches/
--   2026-06-13-tq6-library-hardening-repair.sql
-- - Verification after post-account SQL:
--   TABLES=357
--   USERS=2
--   FOLDERS=21
--   RESOURCES=106
--   QURAN_ROOTS=1
--   QURAN_SOURCES=106
--   DOUBLE_EMBED=0
--   CONTENT_MODE=1
--
-- Default teacher eligibility:
-- - Created two active teacher_subject_classes for the default teacher:
--   - Launch My Deen Journey
--   - Launch Well Being
-- - Verification:
--   TSC_TOTAL=2
--   CLASSES=2
--   CLASS_SUBJECTS=2
--
-- TQ7.5 automation catalog:
-- - First dry-run stopped safely because to_quran_adhkar_dua_banks.md was
--   missing from the deployed package.
-- - After uploading that source file and adding .htaccess deny coverage for
--   markdown/source files, the dry-run reported:
--   69 created, 0 updated, 0 skipped.
-- - Guarded write command:
--   /opt/alt/php83/usr/bin/php artisan toquran:install-automation-catalog \
--     --teacher-email=drosamaqandil@gmail.com \
--     --confirm-db=u504065335_to_quran
-- - Write result:
--   665 created, 224 updated, 0 skipped.
-- - Verification:
--   REGISTRY=665
--   MDS_TEMPLATES=14
--   MDS_VERSIONS=79
--   MDS_TASKS=147
--   MDS_VERSION_TASKS=371
--   SERIES_TASKS=1
--   SERIES_VERSIONS=1
--   SERIES_ITEMS=52
--   DUA_TEXT_SOURCES=52
--
-- Final app DB verification:
--   TABLES=357
--   USERS=2
--   SMOKE_USERS=0
--   ROLES=7
--   TEACHER_SUBJECT_CLASSES=2
--   QURAN_REPETITION_ROOTS=1
--   QURAN_SOURCES=106
--   DUA_TEXT_SOURCES=52
--   CATALOG_REGISTRY=665
--   SERIES_ITEMS=52
--   PASSWORD_RESET_ROWS=1
--
-- HTTP smoke:
-- - https://app.toquran.org/login returned 200 on PHP 8.3.31.
-- - After root asset rewrite correction, public visual assets resolve to
--   the To Quran public files:
--   /assets/img/logo/logo.png returned 200 with 793150 bytes
--   /assets/img/favicon/favicon.ico returned 200 with 56738 bytes
-- - Follow-up branding sweep replaced inherited template OG/default metadata,
--   PWA theme color, root fallback logo/favicon files, legacy Week 14 page
--   titles, Language and Literature fallback copy, and Atom-hosted journey
--   background references. Focused scan over active app/config/view paths
--   found no remaining Week14, Week 14, Pixinvent, Vuexy, Atom Learning,
--   atomlearning, IB Mastery, or Language and Literature strings after
--   excluding archived Atom reference views.
-- - https://toquran.org/appdashboard/login returned 403, confirming the app
--   is not executable from the main website path.
-- - Source/private deny checks returned 403:
--   /.env, /composer.json, /composer.lock, /artisan, /package.json,
--   /vite.config.js, /vendor/autoload.php, /database/, /routes/web.php,
--   /storage/logs/, /to_quran_adhkar_dua_banks.md.
-- - Public storage smoke:
--   /storage/gifts/5fshNgvuWGk9u5DnqcNLdedoBzaP3kxkCbOtdXB8.png returned 200.
--
-- 2026-06-22 document viewer follow-up:
-- - Deployed the scoped external document viewer code/config plus corrected
--   root/public favicon files directly to the app path.
-- - Remote backup before overwrite:
--   /home/u504065335/tq9-doc-viewer-backup-20260621-222445
-- - Refreshed Laravel caches:
--   optimize:clear, config:cache, view:cache, route:cache.
-- - Production favicon checks returned 200 image/x-icon with 21086 bytes:
--   /favicon.ico
--   /assets/img/favicon/favicon.ico
-- - Real demo task PDF snapshot smoke:
--   /storage/attachments/general-library-resource-181/
--   79946e8a-65ac-4396-9211-93cacc86303d.pdf returned 200 application/pdf
--   with 176914 bytes.
-- - Google gview smoke for that same task snapshot returned 200 with the
--   expected PDF title.
-- - Production Library source files remain on Laravel local/private storage;
--   task delivery uses public attachment snapshots, which are the URLs used
--   by Google/Microsoft viewers.
-- - Office-file smoke is still pending because no production Office resource
--   existed at the time of this check.
--
-- Authenticated production smoke after owner-updated launch passwords:
-- - Superadmin login succeeded for the owner account.
-- - Superadmin routes returned 200 with no fatal/error or inherited-branding
--   markers:
--   /admin/staff
--   /admin/teacher-class-assignments
--   /admin/bookings
--   /admin/bookings/intake-review
--   /admin/bookings/transferred
--   /admin/library
--   /admin/gifts
--   /admin/students
--   /teacher/library
--   /teacher/vocabulary/games/launch
--   /vocabulary/games
-- - Teacher login succeeded for the default teacher account.
-- - Teacher routes returned 200 with no fatal/error or inherited-branding
--   markers:
--   /teacher/classes
--   /teacher/library
--   /teacher/library/manage
--   /teacher/vocabulary/games/launch
--   /vocabulary/games
--   /teacher/daily-sessions/subjects
--   /teacher/differentiated-tasks/subjects
--   /teacher/series-tasks/subjects
-- - Teacher negative authorization check:
--   /admin/staff returned 403.
-- - /teacher/journey without student_id/teachersubjectid returned 404 because
--   the controller intentionally resolves an authorized teacher-subject/student
--   pair before rendering. Re-test Journey after the demo family exists.
-- - Private/source deny checks returned 403:
--   /.env, /.gitignore, /composer.json, /composer.lock, /artisan,
--   /package.json, /phpunit.xml, /vite.config.js, /app/, /vendor/,
--   /vendor/autoload.php, /database/, /routes/web.php, /storage/logs/,
--   /to_quran_adhkar_dua_banks.md.
-- - Public asset checks returned 200:
--   /login
--   /assets/img/logo/logo.png
--   /assets/img/logo/logo-dark.png
--   /assets/img/favicon/favicon.ico
--
-- Server-side production sanity after authenticated smoke:
-- - PHP runtime: 8.3.31
-- - storage writable: yes
-- - bootstrap/cache writable: yes
-- - public/storage symlink: present
-- - .env present
-- - route cache present
-- - config cache present
-- - DB target: u504065335_to_quran
-- - Table count: 357
-- - Users: 2
-- - Smoke users: 0
-- - Roles: 7
-- - Bookings: 1
-- - Students: 0
-- - Teacher subject assignments: 2
-- - queue:failed reported no failed jobs.
-- - artisan schedule:list reported:
--   daily:publish-midnight daily at 00:00
--   tasks:auto-approve-trusted-children daily at 00:10
--
-- Remaining Hostinger panel action:
-- - Hostinger SSH does not expose a crontab command, so the Laravel scheduler
--   could not be installed from SSH. Add the scheduler in Hostinger Cron Jobs:
--   cd /home/u504065335/domains/toquran.org/public_html/appdashboard &&
--   /opt/alt/php83/usr/bin/php artisan schedule:run >> /dev/null 2>&1
--   with a one-minute cadence if Hostinger allows it, or the shortest cadence
--   Hostinger supports.
--
-- Remaining launch handoff:
-- - Continue in the public website repo only after this app readiness note is
--   committed/pushed.
-- - Website next steps: create private website .env against the same DB, run
--   website cache/build checks, and run public booking/contact smoke.

-- 2026-06-21 app follow-up deployment:
-- - Pushed branch codex/tq9-launch-readiness through commit e2ba8f6.
-- - Deployed only the runtime files needed for the demo-family command and
--   review fixes to the existing package deployment:
--   .htaccess
--   app/Console/Commands/BootstrapDemoFamily.php
--   app/Services/Library/LibraryResourceValidator.php
--   resources/views/vocabulary/games/custom-launch.blade.php
-- - Did not upload .env, storage, vendor, node_modules, docs, tests, raw SQL,
--   or DB backup artifacts.
-- - Remote syntax checks passed on PHP 8.3.31 for:
--   app/Console/Commands/BootstrapDemoFamily.php
--   app/Services/Library/LibraryResourceValidator.php
-- - Refreshed Laravel caches:
--   artisan optimize:clear
--   artisan config:cache
--   artisan view:cache
--   artisan route:cache
-- - Verified artisan command registration:
--   toquran:bootstrap-demo-family
-- - Production dry-run only command:
--   /opt/alt/php83/usr/bin/php artisan toquran:bootstrap-demo-family \
--     --dry-run \
--     --confirm-db=u504065335_to_quran
-- - Dry-run result:
--   Demo family dry-run passed. No data was written.
--   DB: u504065335_to_quran
--   Teacher: drosamaqandil@gmail.com
--   Library resources: 84
--   Quran repetition resources: 11
--   Family reference: TQDEMO-001
-- - Read-only post-dry-run no-write check:
--   TQDEMO_BOOKINGS=0
--   TQDEMO_STUDENTS=0

-- 2026-06-21 demo family production write:
-- - Owner explicitly approved the real production command after the dry-run.
-- - Approved command:
--   /opt/alt/php83/usr/bin/php artisan toquran:bootstrap-demo-family \
--     --confirm-db=u504065335_to_quran
-- - First write attempt exposed a production-schema mismatch in the booking
--   scaffold before a clean success output was captured:
--   bookings does not own booking_children workflow columns such as
--   consultation_status/evaluation_outcome/meeting_disposition/transfer_status.
-- - Verified before retry that the failed attempt had not duplicated demo
--   rows:
--   TQDEMO_BOOKINGS=0
--   TQDEMO_STUDENTS=0
-- - Fix committed locally as:
--   810fb31 Fix demo family booking scaffold for production schema
-- - Deployed only:
--   app/Console/Commands/BootstrapDemoFamily.php
-- - Remote syntax/caches:
--   /opt/alt/php83/usr/bin/php -l app/Console/Commands/BootstrapDemoFamily.php
--   artisan optimize:clear
--   artisan config:cache
--   artisan route:cache
--   artisan view:cache
-- - Second production dry-run passed against DB u504065335_to_quran.
-- - Idempotent real command completed successfully:
--   booking: 2
--   yusuf: 1
--   maryam: 2
--   omar: 3
-- - Final production verification:
--   BOOKINGS=1
--   STUDENTS=3
--   STUDENT_USERS=3
--   ACTIVE_SUBJECT_LINKS=12
--   GIFTS_TOTAL=60
--   GIFTS_REDEEMED=30
--   SESSIONS=583
--   TASKS=635
--   TASK_PIVOTS=635
--   ATTACHMENTS=100
--   YOUTUBE_ATTACHMENTS=36
--   FILE_ATTACHMENTS=64
--   REWARD_LEDGER=580
--   FAILED_JOBS=0
-- - Production activation/email smoke remains a separate owner-approved step
--   through the normal family lifecycle flow.

-- 2026-06-21 activation/login follow-up:
-- - Owner reported that demo login failed before manual activation and no
--   emails were received after using the admin activation UI.
-- - Server-side credential verification:
--   Demo_PT1244 / osama.salem0217@gmail.com status=active, password hash checks
--   for the recoverable credential.
--   YU101, MA101, and OM101 status=active, password hashes check for the
--   recoverable credential.
-- - Lifecycle gate verification:
--   parent lifecycle_status=active
--   all three demo students account_status=active
-- - HTTPS login POST checks:
--   YU101 redirected to https://app.toquran.org/student/workplace
--   osama.salem0217@gmail.com redirected to https://app.toquran.org/students
-- - Email diagnosis:
--   activation UI had queued 4 database jobs with attempts=0:
--   one SendParentActivationEmailJob and three SendChildActivationEmailJob rows.
--   Hostinger scheduler/queue worker was not processing them automatically.
-- - Processed the four queued activation jobs with:
--   /opt/alt/php83/usr/bin/php artisan queue:work --once --stop-when-empty --tries=1
--   repeated four times.
-- - Queue verification after processing:
--   JOBS=0
--   FAILED_JOBS=0
-- - email_delivery_claims verification:
--   parent_activation:first:1 status=sent
--   child_activation:first:1 status=sent
--   child_activation:first:2 status=sent
--   child_activation:first:3 status=sent

-- 2026-06-21 demo family gift/Points Lab polish deployment:
-- - Owner explicitly approved deploying the demo gift image and Points Lab
--   follow-up after commit:
--   84e8d1d Polish demo family behavior and gift images
-- - Deployed only runtime files/assets needed for this follow-up:
--   app/Console/Commands/BootstrapDemoFamily.php
--   resources/views/livewire/teacher/reward-discipline-points.blade.php
--   resources/demo-gifts/** (30 image files)
-- - Did not upload .env, vendor, node_modules, tests, raw SQL, storage logs,
--   or DB backup artifacts.
-- - Remote syntax/caches:
--   /opt/alt/php83/usr/bin/php -l app/Console/Commands/BootstrapDemoFamily.php
--   artisan optimize:clear
--   artisan config:cache
--   artisan route:cache
--   artisan view:cache
-- - Production dry-run passed:
--   /opt/alt/php83/usr/bin/php artisan toquran:bootstrap-demo-family \
--     --dry-run \
--     --confirm-db=u504065335_to_quran
--   DB: u504065335_to_quran
--   Teacher: drosamaqandil@gmail.com
--   Library resources: 84
--   Quran repetition resources: 11
--   Family reference: TQDEMO-001
-- - Idempotent real command completed successfully:
--   /opt/alt/php83/usr/bin/php artisan toquran:bootstrap-demo-family \
--     --confirm-db=u504065335_to_quran
--   booking: 2
--   yusuf: 1
--   maryam: 2
--   omar: 3
-- - Final read-only verification:
--   REDEEMED_WITH_IMAGES=30
--   DEMO_TITLE_ROWS=0
--   DEMO_DESCRIPTION_ROWS=0
--   LINKED_BEHAVIOR_ROWS=13
--   storage/app/public/gifts/demo-family file count=30
--   sample image URL https://app.toquran.org/storage/gifts/demo-family/Yusuf/Sticker-Pack.webp returned 200 image/webp

-- 2026-06-21 demo family active-gift image repair:
-- - Owner reported that manually uploaded images for open/active demo rewards
--   disappeared after the demo command was rerun.
-- - Cause:
--   gifts 11-20 do not have bundled demo images. The command was recomputing
--   gift_image from bundled assets and overwrote existing manual image paths
--   with NULL.
-- - Local code fix:
--   app/Console/Commands/BootstrapDemoFamily.php now preserves an existing
--   gift_image when no bundled demo image exists for the gift.
--   tests/Feature/CoreLms/BootstrapDemoFamilyCommandTest.php now covers this
--   idempotency case.
-- - Points Lab polish:
--   resources/views/livewire/teacher/reward-discipline-points.blade.php now
--   renders behavior-count badges as the plain number, not x{number}.
-- - Local verification:
--   php artisan test tests/Feature/CoreLms/BootstrapDemoFamilyCommandTest.php \
--     tests/Feature/MyDeenJourneyLaunchDefaultsTest.php \
--     tests/Feature/AdminRewardDisciplinePointsTest.php
--   Result: 7 passed, 63 assertions.
-- - Production repair:
--   Deployed the two runtime files above.
--   Ran a temporary guarded Laravel script in appdashboard to restore gift_image
--   paths for student_gifts ids 31-60 from the already-uploaded files under
--   storage/app/public/gifts/.
--   The temporary script verified database() = u504065335_to_quran and verified
--   every target file existed before updating rows, then it was deleted.
-- - Production guard verification:
--   Reran:
--   /opt/alt/php83/usr/bin/php artisan toquran:bootstrap-demo-family \
--     --confirm-db=u504065335_to_quran
--   Then verified:
--   future_images=30
--   all_demo_images=60
--   blank_future=0
--   has_x_badge=false
-- - Public file smoke:
--   https://app.toquran.org/storage/gifts/CI5BwKkXldGbSbE1NGdOVD3gFwEbvNLuZvN7cU7r.webp
--   returned 200 image/webp, length 82680.

-- 2026-06-21 demo family Points Lab history expansion:
-- - Owner requested a richer showcase history where behavior cards show many
--   different count bubbles such as 25, 18, 50, and 31 for each child.
-- - Local code update:
--   app/Console/Commands/BootstrapDemoFamily.php now seeds a curated
--   per-child Points Lab distribution across Positive, Slip, and a small
--   number of Red Flag cards. The command deletes/recreates only its known
--   demo timestamps, then reconciles reward ledger/totals back to the existing
--   demo gift-point targets so gift #11 remains open.
-- - Local verification:
--   php artisan test tests/Feature/CoreLms/BootstrapDemoFamilyCommandTest.php \
--     tests/Feature/MyDeenJourneyLaunchDefaultsTest.php \
--     tests/Feature/AdminRewardDisciplinePointsTest.php
--   Result: 7 passed, 66 assertions.
-- - Production deployment:
--   Deployed app/Console/Commands/BootstrapDemoFamily.php only.
--   /opt/alt/php83/usr/bin/php -l app/Console/Commands/BootstrapDemoFamily.php
--   returned no syntax errors.
--   Ran:
--   /opt/alt/php83/usr/bin/php artisan optimize:clear
--   /opt/alt/php83/usr/bin/php artisan toquran:bootstrap-demo-family \
--     --confirm-db=u504065335_to_quran
-- - Production verification:
--   linked demo discipline rows for the three students=988
--   Yusuf Good Effort=31
--   Maryam Responsibility=50
--   Omar Self-Control=50
--   Omar Good Deed=40
--   future_images=30
--   blank_future=0
--   gift_11_reached=0
-- - Temporary production verification script was deleted after use.

-- 2026-06-21 PWA icon and Behavior Lab theme-color polish:
-- - Owner requested:
--   1) app install icon should show To Quran branding instead of the temporary
--      TQ shortcut icon;
--   2) green Positive/Behavior Lab card tones should use the To Quran theme
--      color.
-- - Local code/assets changed:
--   app/Http/Controllers/PwaController.php now exposes manifest theme_color
--   #c9a24d.
--   public/pwa/icons/toquran-*.png were regenerated from the gold To Quran
--   tree/book mark asset.
--   app/Livewire/Teacher/RewardDisciplinePoints.php and
--   resources/views/livewire/teacher/reward-discipline-points.blade.php now
--   render Positive Behavior Lab controls, cards, counts, history badges, and
--   analysis bars with Bootstrap primary/theme color instead of success green.
--   tests/Feature/PwaInstallabilityTest.php now asserts the gold manifest theme
--   color and required icon files.
-- - Local verification:
--   php -l app/Http/Controllers/PwaController.php
--   php -l app/Livewire/Teacher/RewardDisciplinePoints.php
--   php artisan test tests/Feature/PwaInstallabilityTest.php
--   Result: 3 passed, 32 assertions.
--   php artisan test tests/Feature/AdminRewardDisciplinePointsTest.php
--   Result: 1 passed, 6 assertions.
--   php artisan test tests/Unit/BookingServiceInterestTest.php \
--     tests/Feature/BookingTransferGatingTest.php \
--     --filter "selected|service|Islamic|Quran Literature|optional|subject"
--   Result: 13 passed, 93 assertions.
-- - Production deployment:
--   Uploaded only:
--   app/Http/Controllers/PwaController.php
--   app/Livewire/Teacher/RewardDisciplinePoints.php
--   resources/views/livewire/teacher/reward-discipline-points.blade.php
--   public/pwa/icons/toquran-apple-touch-icon.png
--   public/pwa/icons/toquran-icon-192.png
--   public/pwa/icons/toquran-icon-512.png
--   public/pwa/icons/toquran-maskable-512.png
--   Remote syntax/caches:
--   /opt/alt/php83/usr/bin/php -l app/Http/Controllers/PwaController.php
--   /opt/alt/php83/usr/bin/php -l app/Livewire/Teacher/RewardDisciplinePoints.php
--   /opt/alt/php83/usr/bin/php artisan optimize:clear
--   /opt/alt/php83/usr/bin/php artisan config:cache
--   /opt/alt/php83/usr/bin/php artisan route:cache
--   /opt/alt/php83/usr/bin/php artisan view:cache
-- - Public HTTP verification:
--   https://app.toquran.org/login returned 200 and included manifest,
--   #c9a24d theme-color, and toquran-apple-touch-icon.png.
--   https://app.toquran.org/manifest.webmanifest returned 200,
--   Content-Type application/manifest+json; charset=UTF-8, and
--   theme_color #c9a24d.
--   https://app.toquran.org/pwa/icons/toquran-icon-192.png returned 200
--   image/png length 48404.
--   https://app.toquran.org/pwa/icons/toquran-icon-512.png returned 200
--   image/png length 318462.
--   https://app.toquran.org/pwa/icons/toquran-maskable-512.png returned 200
--   image/png length 225637.
--   https://app.toquran.org/pwa/icons/toquran-apple-touch-icon.png returned
--   200 image/png length 43083.

-- 2026-06-21 breadcrumb/demo-title/starter-catalog follow-up:
-- - Owner tested the local PDF.js protected-PDF experiment and rejected it
--   because it added a second page-navigation layer and made mobile PDFs feel
--   cramped. The PDF.js experiment was reverted before this deployment.
-- - Local code updates kept for deployment:
--   app/Console/Commands/BootstrapDemoFamily.php removes the visible [Demo]
--   prefix from newly reconciled demo class-session titles while preserving
--   idempotent lookup through TQDEMO-001 session material markers.
--   resources/views/layouts/sections/navbar/navbar-partial.blade.php removes
--   Livewire navigation from breadcrumb back/title links so mobile sidebar
--   state is reset by normal page navigation.
--   app/Livewire/Admin/StarterCatalogInstaller.php and
--   app/Support/ToQuranAutomationCatalog/AutomationCatalogInstaller.php include
--   starter-catalog review hardening: shared registry-table constant, explicit
--   auth check, safer teacher id handling, and generic error logging.
-- - Local verification:
--   npm run build
--   php artisan test tests/Feature/CoreLms/LifecycleGateTest.php --filter=attachment_study_viewer
--   php artisan test tests/Feature/CoreLms/LibraryAuthTest.php \
--     tests/Feature/CoreLms/ProtectedLibraryResourceAccessTest.php \
--     tests/Feature/CoreLms/LibraryManagerTest.php \
--     tests/Feature/CoreLms/BootstrapDemoFamilyCommandTest.php \
--     tests/Feature/CoreLms/StarterCatalogInstallerUiTest.php
--   Result: 50 passed, 305 assertions across the focused runs.
--   git diff --check returned clean.
-- - Production deployment:
--   Working tree based on local HEAD 1cfb29c; deployed only runtime files:
--   app/Console/Commands/BootstrapDemoFamily.php
--   app/Livewire/Admin/StarterCatalogInstaller.php
--   app/Support/ToQuranAutomationCatalog/AutomationCatalogInstaller.php
--   resources/views/layouts/sections/navbar/navbar-partial.blade.php
-- - Remote backup of replaced files:
--   /home/u504065335/domains/toquran.org/public_html/appdashboard/storage/app/private/deployment-file-backups/20260621-211542-pdf-revert-navbar-catalog
-- - Remote syntax/caches:
--   /opt/alt/php83/usr/bin/php -l passed for all uploaded PHP/Blade files.
--   /opt/alt/php83/usr/bin/php artisan optimize:clear
--   /opt/alt/php83/usr/bin/php artisan config:cache
--   /opt/alt/php83/usr/bin/php artisan route:cache
--   /opt/alt/php83/usr/bin/php artisan view:cache
-- - Production verification:
--   https://app.toquran.org/login returned 200 and included To Quran branding.
--   Source/private deny checks returned 403 for:
--   /.env, /composer.json, /vendor/autoload.php, /database/, /routes/web.php.
--   Remote scan over app/resources/public build manifest found no
--   ToQuranPdfViewer, pdfjs-dist, or data-tq-pdf-viewer markers.

-- 2026-06-22 final runtime polish and document-viewer deployment:
-- - Local commit:
--   7a91461 Finalize TQ9 launch readiness polish
-- - Local code updates included:
--   protected document viewer provider support for Google PDF viewer and
--   Microsoft Office viewer using existing public storage URLs;
--   explicit gold primary-color swatch in the Vuexy customizer so choosing
--   another color does not remove the To Quran gold option;
--   refreshed To Quran favicon assets;
--   starter-catalog UI hardening;
--   demo-family command/history polish.
-- - Local verification:
--   npm run build
--   php artisan test tests/Unit/PrimaryColorCssTest.php \
--     tests/Unit/TaskAttachmentPresenterTest.php
--   Result: 15 passed, 44 assertions.
--   php artisan test tests/Feature/CoreLms/StarterCatalogInstallerUiTest.php \
--     tests/Feature/CoreLms/BootstrapDemoFamilyCommandTest.php
--   Result: 4 passed, 59 assertions.
--   php artisan test tests/Feature/CoreLms/LifecycleGateTest.php \
--     --filter=attachment_study_viewer
--   Result: 6 passed, 63 assertions.
--   git diff --check returned clean.
-- - Production deployment:
--   Uploaded runtime files, favicons, and Vite build folders to:
--   /home/u504065335/domains/toquran.org/public_html/appdashboard
-- - Remote backup of replaced files:
--   /home/u504065335/tq9-app-runtime-backup-20260622-020902
-- - Remote cache refresh:
--   /opt/alt/php83/usr/bin/php artisan optimize:clear
--   /opt/alt/php83/usr/bin/php artisan config:cache
--   /opt/alt/php83/usr/bin/php artisan route:cache
--   /opt/alt/php83/usr/bin/php artisan view:cache
-- - Production verification:
--   https://app.toquran.org/login returned 200 with title To Quran | Login.
--   https://app.toquran.org/favicon.ico returned 200 image/x-icon,
--   length 21086.
--   A real Tajweed Beginner's Book PDF under /storage returned 200
--   application/pdf, length 176914.
--   Google gview for that same production PDF returned 200 text/html.
--   Production storage scan found no existing Office files to smoke against
--   Microsoft viewer during this pass.

-- 2026-06-22 browser/PWA push notifications deployment:
-- - Local code updates included:
--   minishlink/web-push Composer dependency;
--   push_subscriptions model/table patch;
--   browser push config, service, controller routes, and root service-worker;
--   parent/student opt-in controls;
--   parent task-review push after StudentTaskApprovalService::putToReview();
--   parent/student reward-reached push after RewardProgressionService advances
--   newly reached gifts.
-- - Local verification before deployment:
--   composer validate --no-check-publish
--   php artisan route:list --name=browser-push
--   php artisan route:list --path=service-worker
--   php artisan test tests\Feature\CoreLms\BrowserPushNotificationsTest.php \
--     tests\Unit\StudentTaskApprovalServiceTest.php
--   Result: 30 passed, 95 assertions.
--   git diff --check returned clean.
-- - Production deployment:
--   Uploaded scoped runtime package:
--   /home/u504065335/toquranapp-browser-push-20260622-221212.tgz
--   Extracted into:
--   /home/u504065335/domains/toquran.org/public_html/appdashboard
-- - Remote backup of replaced files and pre-change DB:
--   /home/u504065335/tq9-browser-push-tail-backup-20260622-192321
--   DB backup file:
--   /home/u504065335/tq9-browser-push-tail-backup-20260622-192321/u504065335_to_quran-before-browser-push-tail.sql.gz
-- - SQL execution:
--   Applied database/manual/patches/2026-06-22-create-browser-push-subscriptions.sql
--   with @toquran_confirm_real_db_target='u504065335_to_quran'.
--   Verification returned push_subscription_tables=1.
-- - Remote dependency/env/cache:
--   COMPOSER_ALLOW_SUPERUSER=1 /opt/alt/php83/usr/bin/php $(which composer)
--     install --no-dev --optimize-autoloader --no-interaction
--   Browser push was enabled in production .env with VAPID keys configured
--   and subject mailto:support@toquran.org.
--   /opt/alt/php83/usr/bin/php artisan optimize:clear
--   /opt/alt/php83/usr/bin/php artisan config:cache
--   /opt/alt/php83/usr/bin/php artisan route:cache
--   /opt/alt/php83/usr/bin/php artisan view:cache
-- - Production verification:
--   Remote config check returned:
--   {"enabled":true,"configured":true,"subject":"mailto:support@toquran.org"}
--   Route checks confirmed browser-push routes and /service-worker.js route.
--   https://app.toquran.org/service-worker.js returned 200 with
--   Content-Type application/javascript; charset=UTF-8,
--   Service-Worker-Allowed: /, and no-cache headers.
--   Service-worker body contained push and notificationclick handlers and
--   did not contain a fetch handler.
--   https://app.toquran.org/login returned 200 with current secure cookies
--   and security headers.
-- - Remaining manual smoke:
--   Parent/student must opt in on a real supported phone/browser or installed
--   PWA, receive a test push, then verify task-review and reward-reached
--   notifications.

-- 2026-06-22 browser push notification badge follow-up:
-- - Owner real-device smoke confirmed the browser push test notification
--   worked, made the normal device sound, and opened the installed app when
--   tapped.
-- - The Android status-bar badge rendered as a plain white square because
--   browser-push payloads reused the full-color maskable app icon for the
--   notification `badge`.
-- - Local fix:
--   added public/pwa/icons/toquran-notification-badge.png as a transparent
--   monochrome tree/book notification badge;
--   app/Http/Controllers/PushServiceWorkerController.php now uses it as
--   DEFAULT_BADGE;
--   app/Services/BrowserPush/BrowserPushService.php sends it in push payloads.
-- - Local verification:
--   php -l app/Http/Controllers/PushServiceWorkerController.php
--   php -l app/Services/BrowserPush/BrowserPushService.php
--   php artisan test tests\Feature\CoreLms\BrowserPushNotificationsTest.php
--   Result: 4 passed, 16 assertions.
-- - Production deployment:
--   Uploaded only the badge icon and the two runtime PHP files.
--   Remote backup:
--   /home/u504065335/tq9-browser-push-badge-backup-20260622-234151
--   Refreshed Laravel caches.
-- - Production verification:
--   https://app.toquran.org/service-worker.js contains
--   /pwa/icons/toquran-notification-badge.png.
--   https://app.toquran.org/pwa/icons/toquran-notification-badge.png
--   returned 200 image/png, length 1055.
--   Service worker still has push=1, notificationclick=1, fetch=0.

-- 2026-06-22 browser push notification badge tree-only polish:
-- - Owner smoke confirmed the first dedicated badge no longer rendered as a
--   blank square, but the tiny Android status-bar mark still showed a visible
--   book/base line under the tree.
-- - Local fix:
--   regenerated public/pwa/icons/toquran-notification-badge.png as a
--   transparent monochrome tree-only silhouette with no book/base line.
-- - Local verification:
--   php artisan test tests\Feature\CoreLms\BrowserPushNotificationsTest.php
--   Result: 4 passed, 16 assertions.
--   git diff --check returned clean.
-- - Production deployment:
--   Uploaded only public/pwa/icons/toquran-notification-badge.png.
--   Remote backup:
--   /home/u504065335/tq9-browser-push-badge-tree-polish-backup-20260623-000118.png
-- - Production verification:
--   https://app.toquran.org/pwa/icons/toquran-notification-badge.png
--   returned 200 image/png, length 1005.
--   Remote SHA-256:
--   866f57a60333b295f3188afac99cf09f9caf09dfbdd2fded70963f8531f6b365.

-- 2026-06-23 browser push parent/student launch UX follow-up:
-- - Owner decision: after production smoke passed, parent/student launch UI
--   should not keep showing Test or Turn off controls every time they log in.
-- - Local fix:
--   resources/views/components/browser-push-control.blade.php now shows only
--   the Enable action when the current browser is not subscribed. If the
--   current browser already has a push subscription, the whole opt-in card
--   stays hidden.
-- - Local verification:
--   php artisan test tests\Feature\CoreLms\BrowserPushNotificationsTest.php
--   Result: 4 passed, 16 assertions.
--   Component grep found no Test, Turn off, data-browser-push-test,
--   data-browser-push-disable, or unsubscribe UI wiring.
-- - Production deployment:
--   Uploaded only resources/views/components/browser-push-control.blade.php.
--   Remote backup:
--   /home/u504065335/tq9-browser-push-control-launch-ux-backup-20260623-001723.blade.php
--   Cleared and rebuilt Laravel view cache.

-- 2026-06-23 demo child login email domain normalization:
-- - Owner asked why demo child login emails used @app.toquran.org instead of
--   @toquran.org. The creation path was hard-coded in
--   app/Services/BookingTransferService.php.
-- - Local fix:
--   BookingTransferService now creates future child login emails as
--   {student_username}@toquran.org.
--   tests/Feature/BookingTransferLifecycleInitTest.php was updated to match.
-- - Local verification:
--   php artisan test tests\Feature\BookingTransferLifecycleInitTest.php
--   Result: 6 passed, 56 assertions.
--   Guarded SQL patch syntax was checked locally with the confirmation
--   variable intentionally absent:
--   database/manual/patches/2026-06-23-normalize-demo-child-login-email-domain.sql
-- - Production deployment:
--   Uploaded app/Services/BookingTransferService.php and the guarded SQL patch.
--   Fresh production backup:
--   /home/u504065335/domains/toquran.org/public_html/appdashboard/_deploy_backups/20260622-214004-before-child-login-email-domain-normalization/u504065335_to_quran-before-child-login-email-domain-normalization.sql.gz
--   Ran the SQL patch with @toquran_confirm_real_db_target='u504065335_to_quran'.
--   Refreshed Laravel optimize/config/route/view caches.
-- - Production verification:
--   Before:
--     MA101@app.toquran.org
--     OM101@app.toquran.org
--     YU101@app.toquran.org
--   After users.email:
--     MA101@toquran.org
--     OM101@toquran.org
--     YU101@toquran.org
--   After students.student_email:
--     MA101@toquran.org
--     OM101@toquran.org
--     YU101@toquran.org

-- 2026-06-23 child reset synthetic-email fallback guard:
-- - External review found that public forgot-password requests for a child
--   account without a parent email route could fall through to the child
--   synthetic login email. Because child login emails now use @toquran.org,
--   this should fail closed instead of attempting delivery to the child login.
-- - Local fix:
--   app/Models/User.php now stops child reset delivery once the user is
--   identified as a child account and no parent email/user email exists.
-- - Local verification:
--   php artisan test tests\Feature\PasswordResetTest.php
--   Result: 11 passed, 40 assertions.
--   php artisan test tests\Feature\BookingTransferLifecycleInitTest.php tests\Feature\PasswordResetTest.php
--   Result: 17 passed, 96 assertions.
-- - Production deployment:
--   Uploaded only app/Models/User.php.
--   Remote backup:
--   /home/u504065335/domains/toquran.org/public_html/appdashboard/app/Models/User.php.bak-20260623-child-reset-route
--   Cleared Laravel optimize/cache/bootstrap files.
-- - Production verification:
--   Remote artisan tinker confirmed the normalized demo child email domain
--   still exists for YU101@toquran.org after deployment.

-- 2026-06-23 child reset orphan/student-row hardening follow-up:
-- - External review found one remaining low-risk edge case: a child user with
--   a students row but a missing/dangling parent relation could still skip the
--   child reset branch and fall through to the generic reset notification.
-- - Local fix:
--   app/Models/User.php now treats any user with an attached students row as
--   a child reset request. It sends only when a parent email or linked parent
--   user email is available; otherwise it stops without sending.
-- - Local verification:
--   php artisan test tests\Feature\PasswordResetTest.php
--   Result: 13 passed, 44 assertions.
--   php artisan test tests\Feature\BookingTransferLifecycleInitTest.php tests\Feature\PasswordResetTest.php
--   Result: 19 passed, 100 assertions.
--   git diff --check returned clean for the touched reset files.
-- - Production deployment:
--   Uploaded only app/Models/User.php.
--   Remote backup:
--   /home/u504065335/domains/toquran.org/public_html/appdashboard/app/Models/User.php.bak-20260623-child-reset-orphan-guard
--   Cleared Laravel optimize/cache/bootstrap files.
