-- Execution note: TQ5 My Deen Journey Good Job popup category flag fix
-- Date: 2026-06-06
-- Repo/branch: toquranapp / codex/tq5-my-deen-journey-launch
--
-- Target verified:
--   DB_DATABASE=u504065335_to_quran
--
-- Backup evidence:
--   database/manual/backups/2026-06-06-u504065335_to_quran-before-mdj-good-job-popup-flag-fix.sql
--   Focused tables: reward_discipline_transfer, reward_discipline_points.
--
-- Patch executed:
--   database/manual/patches/2026-06-06-mdj-good-job-popup-flag-fix.sql
--
-- Success evidence on u504065335_to_quran:
--   TQ5 MDJ Good Job popup category flag guard passed.
--   reward_discipline_transfer / Good Job / Positive / teacher_desc=1 / row_count=1
--   reward_discipline_points / Good Job / Positive / teacher_desc=1 / row_count=11
--
-- Guard-failure evidence:
--   The same patch was run against toquranapp_local and returned:
--   REFUSING TQ5 MDJ Good Job popup category flag fix: wrong DB, missing confirmation, or subject 15/16 identity mismatch. Updates are gated off.
--
-- Behavioral note:
--   `Good Job` is the Positive category card. It should open the behavior modal
--   for parent and teacher quick actions, not add points instantly like a normal
--   behavior card.
