-- TQ9 app production deployment execution note
-- Status: executed on Hostinger on 2026-06-20 after the pre-account DB replay.
-- This is an evidence note only. Do not source this file.
--
-- Target:
-- - App URL: https://app.toquran.org
-- - Hostinger user/home: u504065335 / /home/u504065335
-- - App path:
--   /home/u504065335/domains/toquran.org/public_html/appdashboard
-- - Production DB: u504065335_to_quran
-- - PHP runtime used for app commands: /opt/alt/php83/usr/bin/php (8.3.31)
-- - Composer path: /usr/local/bin/composer
--
-- Secret handling:
-- - SSH, DB, mail, app key, generated account passwords, and reset tokens are
--   not recorded here.
-- - The production .env was written directly on Hostinger with mode 600.
-- - Because temporary SSH/DB credentials were shared during deployment prep,
--   rotate them after website smoke and launch handoff complete.
--
-- Code/package:
-- - Source commit packaged: 2fe1b2dbaf22
-- - Local archive name:
--   toquranapp-deploy-2fe1b2dbaf22-20260620-182346.tgz
-- - Archive size: 175,295,382 bytes
-- - Remote archive:
--   /home/u504065335/toquranapp-deploy-2fe1b2dbaf22-20260620-182346.tgz
-- - Package scan excluded .env, .git, Composer vendor, node_modules, docs,
--   tests, database/manual, raw SQL, and backups.
-- - Package included built assets, app runtime files, public assets, and
--   Library/storage content. The required catalog source file
--   to_quran_adhkar_dua_banks.md was uploaded after the first catalog dry-run
--   reported it missing.
--
-- App install:
-- - composer install --no-dev --optimize-autoloader completed.
-- - composer check-platform-reqs --no-dev passed on PHP 8.3.31.
-- - artisan optimize:clear completed.
-- - artisan config:cache completed.
-- - artisan view:cache completed.
-- - artisan route:cache completed.
-- - public/storage was corrected from a copied directory to the Laravel
--   storage symlink, and root .htaccess rewrites /storage/* to public storage
--   files only when the public file exists.
-- - Visual login smoke then showed the inherited Week14/KL root logo/favicon
--   because Hostinger serves this subdomain from the project root. Root
--   .htaccess was updated to rewrite public asset URLs for /assets, /images,
--   /pwa, and /build into public/ when the public file exists, preserving the
--   private-source deny rules while making asset() resolve to the To Quran
--   public logo/favicon.
--
-- Production .env safe summary:
-- - APP_ENV=production
-- - APP_DEBUG=false
-- - APP_URL=https://app.toquran.org
-- - APP_KEY present
-- - DB target present for u504065335_to_quran
-- - MAIL_* present, with support mailbox identity present
-- - TOQURAN_DEFAULT_TEACHER_EMAIL=drosamaqandil@gmail.com
-- - SESSION_DRIVER=database
-- - QUEUE_CONNECTION=database
-- - CACHE_STORE=database
-- - FILESYSTEM_DISK=local
--
-- Account bootstrap:
-- - Created two launch users only:
--   - owner superadmin (active, super_admin role)
--   - default teacher drosamaqandil@gmail.com (active, teacher role)
-- - Generated one-time passwords were not printed or committed.
-- - A password reset email was sent for the owner superadmin account; mailer
--   returned passwords.sent and one password_reset_tokens row exists.
--
-- Post-account SQL:
-- - Ran database/manual/patches/
--   2026-06-07-tq6-library-folder-mode-and-quran-repetition-import.sql
-- - Ran database/manual/patches/
--   2026-06-13-tq6-library-hardening-repair.sql
-- - Verification after post-account SQL:
--   TABLES=357
--   USERS=2
--   FOLDERS=21
--   RESOURCES=106
--   QURAN_ROOTS=1
--   QURAN_SOURCES=106
--   DOUBLE_EMBED=0
--   CONTENT_MODE=1
--
-- Default teacher eligibility:
-- - Created two active teacher_subject_classes for the default teacher:
--   - Launch My Deen Journey
--   - Launch Well Being
-- - Verification:
--   TSC_TOTAL=2
--   CLASSES=2
--   CLASS_SUBJECTS=2
--
-- TQ7.5 automation catalog:
-- - First dry-run stopped safely because to_quran_adhkar_dua_banks.md was
--   missing from the deployed package.
-- - After uploading that source file and adding .htaccess deny coverage for
--   markdown/source files, the dry-run reported:
--   69 created, 0 updated, 0 skipped.
-- - Guarded write command:
--   /opt/alt/php83/usr/bin/php artisan toquran:install-automation-catalog \
--     --teacher-email=drosamaqandil@gmail.com \
--     --confirm-db=u504065335_to_quran
-- - Write result:
--   665 created, 224 updated, 0 skipped.
-- - Verification:
--   REGISTRY=665
--   MDS_TEMPLATES=14
--   MDS_VERSIONS=79
--   MDS_TASKS=147
--   MDS_VERSION_TASKS=371
--   SERIES_TASKS=1
--   SERIES_VERSIONS=1
--   SERIES_ITEMS=52
--   DUA_TEXT_SOURCES=52
--
-- Final app DB verification:
--   TABLES=357
--   USERS=2
--   SMOKE_USERS=0
--   ROLES=7
--   TEACHER_SUBJECT_CLASSES=2
--   QURAN_REPETITION_ROOTS=1
--   QURAN_SOURCES=106
--   DUA_TEXT_SOURCES=52
--   CATALOG_REGISTRY=665
--   SERIES_ITEMS=52
--   PASSWORD_RESET_ROWS=1
--
-- HTTP smoke:
-- - https://app.toquran.org/login returned 200 on PHP 8.3.31.
-- - After root asset rewrite correction, public visual assets resolve to
--   the To Quran public files:
--   /assets/img/logo/logo.png returned 200 with 793150 bytes
--   /assets/img/favicon/favicon.ico returned 200 with 56738 bytes
-- - Follow-up branding sweep replaced inherited template OG/default metadata,
--   PWA theme color, root fallback logo/favicon files, legacy Week 14 page
--   titles, Language and Literature fallback copy, and Atom-hosted journey
--   background references. Focused scan over active app/config/view paths
--   found no remaining Week14, Week 14, Pixinvent, Vuexy, Atom Learning,
--   atomlearning, IB Mastery, or Language and Literature strings after
--   excluding archived Atom reference views.
-- - https://toquran.org/appdashboard/login returned 403, confirming the app
--   is not executable from the main website path.
-- - Source/private deny checks returned 403:
--   /.env, /composer.json, /composer.lock, /artisan, /package.json,
--   /vite.config.js, /vendor/autoload.php, /database/, /routes/web.php,
--   /storage/logs/, /to_quran_adhkar_dua_banks.md.
-- - Public storage smoke:
--   /storage/gifts/5fshNgvuWGk9u5DnqcNLdedoBzaP3kxkCbOtdXB8.png returned 200.
--
-- Authenticated production smoke after owner-updated launch passwords:
-- - Superadmin login succeeded for the owner account.
-- - Superadmin routes returned 200 with no fatal/error or inherited-branding
--   markers:
--   /admin/staff
--   /admin/teacher-class-assignments
--   /admin/bookings
--   /admin/bookings/intake-review
--   /admin/bookings/transferred
--   /admin/library
--   /admin/gifts
--   /admin/students
--   /teacher/library
--   /teacher/vocabulary/games/launch
--   /vocabulary/games
-- - Teacher login succeeded for the default teacher account.
-- - Teacher routes returned 200 with no fatal/error or inherited-branding
--   markers:
--   /teacher/classes
--   /teacher/library
--   /teacher/library/manage
--   /teacher/vocabulary/games/launch
--   /vocabulary/games
--   /teacher/daily-sessions/subjects
--   /teacher/differentiated-tasks/subjects
--   /teacher/series-tasks/subjects
-- - Teacher negative authorization check:
--   /admin/staff returned 403.
-- - /teacher/journey without student_id/teachersubjectid returned 404 because
--   the controller intentionally resolves an authorized teacher-subject/student
--   pair before rendering. Re-test Journey after the demo family exists.
-- - Private/source deny checks returned 403:
--   /.env, /.gitignore, /composer.json, /composer.lock, /artisan,
--   /package.json, /phpunit.xml, /vite.config.js, /app/, /vendor/,
--   /vendor/autoload.php, /database/, /routes/web.php, /storage/logs/,
--   /to_quran_adhkar_dua_banks.md.
-- - Public asset checks returned 200:
--   /login
--   /assets/img/logo/logo.png
--   /assets/img/logo/logo-dark.png
--   /assets/img/favicon/favicon.ico
--
-- Server-side production sanity after authenticated smoke:
-- - PHP runtime: 8.3.31
-- - storage writable: yes
-- - bootstrap/cache writable: yes
-- - public/storage symlink: present
-- - .env present
-- - route cache present
-- - config cache present
-- - DB target: u504065335_to_quran
-- - Table count: 357
-- - Users: 2
-- - Smoke users: 0
-- - Roles: 7
-- - Bookings: 1
-- - Students: 0
-- - Teacher subject assignments: 2
-- - queue:failed reported no failed jobs.
-- - artisan schedule:list reported:
--   daily:publish-midnight daily at 00:00
--   tasks:auto-approve-trusted-children daily at 00:10
--
-- Remaining Hostinger panel action:
-- - Hostinger SSH does not expose a crontab command, so the Laravel scheduler
--   could not be installed from SSH. Add the scheduler in Hostinger Cron Jobs:
--   cd /home/u504065335/domains/toquran.org/public_html/appdashboard &&
--   /opt/alt/php83/usr/bin/php artisan schedule:run >> /dev/null 2>&1
--   with a one-minute cadence if Hostinger allows it, or the shortest cadence
--   Hostinger supports.
--
-- Remaining launch handoff:
-- - Continue in the public website repo only after this app readiness note is
--   committed/pushed.
-- - Website next steps: create private website .env against the same DB, run
--   website cache/build checks, and run public booking/contact smoke.

-- 2026-06-21 app follow-up deployment:
-- - Pushed branch codex/tq9-launch-readiness through commit e2ba8f6.
-- - Deployed only the runtime files needed for the demo-family command and
--   review fixes to the existing package deployment:
--   .htaccess
--   app/Console/Commands/BootstrapDemoFamily.php
--   app/Services/Library/LibraryResourceValidator.php
--   resources/views/vocabulary/games/custom-launch.blade.php
-- - Did not upload .env, storage, vendor, node_modules, docs, tests, raw SQL,
--   or DB backup artifacts.
-- - Remote syntax checks passed on PHP 8.3.31 for:
--   app/Console/Commands/BootstrapDemoFamily.php
--   app/Services/Library/LibraryResourceValidator.php
-- - Refreshed Laravel caches:
--   artisan optimize:clear
--   artisan config:cache
--   artisan view:cache
--   artisan route:cache
-- - Verified artisan command registration:
--   toquran:bootstrap-demo-family
-- - Production dry-run only command:
--   /opt/alt/php83/usr/bin/php artisan toquran:bootstrap-demo-family \
--     --dry-run \
--     --confirm-db=u504065335_to_quran
-- - Dry-run result:
--   Demo family dry-run passed. No data was written.
--   DB: u504065335_to_quran
--   Teacher: drosamaqandil@gmail.com
--   Library resources: 84
--   Quran repetition resources: 11
--   Family reference: TQDEMO-001
-- - Read-only post-dry-run no-write check:
--   TQDEMO_BOOKINGS=0
--   TQDEMO_STUDENTS=0

-- 2026-06-21 demo family production write:
-- - Owner explicitly approved the real production command after the dry-run.
-- - Approved command:
--   /opt/alt/php83/usr/bin/php artisan toquran:bootstrap-demo-family \
--     --confirm-db=u504065335_to_quran
-- - First write attempt exposed a production-schema mismatch in the booking
--   scaffold before a clean success output was captured:
--   bookings does not own booking_children workflow columns such as
--   consultation_status/evaluation_outcome/meeting_disposition/transfer_status.
-- - Verified before retry that the failed attempt had not duplicated demo
--   rows:
--   TQDEMO_BOOKINGS=0
--   TQDEMO_STUDENTS=0
-- - Fix committed locally as:
--   810fb31 Fix demo family booking scaffold for production schema
-- - Deployed only:
--   app/Console/Commands/BootstrapDemoFamily.php
-- - Remote syntax/caches:
--   /opt/alt/php83/usr/bin/php -l app/Console/Commands/BootstrapDemoFamily.php
--   artisan optimize:clear
--   artisan config:cache
--   artisan route:cache
--   artisan view:cache
-- - Second production dry-run passed against DB u504065335_to_quran.
-- - Idempotent real command completed successfully:
--   booking: 2
--   yusuf: 1
--   maryam: 2
--   omar: 3
-- - Final production verification:
--   BOOKINGS=1
--   STUDENTS=3
--   STUDENT_USERS=3
--   ACTIVE_SUBJECT_LINKS=12
--   GIFTS_TOTAL=60
--   GIFTS_REDEEMED=30
--   SESSIONS=583
--   TASKS=635
--   TASK_PIVOTS=635
--   ATTACHMENTS=100
--   YOUTUBE_ATTACHMENTS=36
--   FILE_ATTACHMENTS=64
--   REWARD_LEDGER=580
--   FAILED_JOBS=0
-- - Production activation/email smoke remains a separate owner-approved step
--   through the normal family lifecycle flow.

-- 2026-06-21 activation/login follow-up:
-- - Owner reported that demo login failed before manual activation and no
--   emails were received after using the admin activation UI.
-- - Server-side credential verification:
--   Demo_PT1244 / osama.salem0217@gmail.com status=active, password hash checks
--   for the recoverable credential.
--   YU101, MA101, and OM101 status=active, password hashes check for the
--   recoverable credential.
-- - Lifecycle gate verification:
--   parent lifecycle_status=active
--   all three demo students account_status=active
-- - HTTPS login POST checks:
--   YU101 redirected to https://app.toquran.org/student/workplace
--   osama.salem0217@gmail.com redirected to https://app.toquran.org/students
-- - Email diagnosis:
--   activation UI had queued 4 database jobs with attempts=0:
--   one SendParentActivationEmailJob and three SendChildActivationEmailJob rows.
--   Hostinger scheduler/queue worker was not processing them automatically.
-- - Processed the four queued activation jobs with:
--   /opt/alt/php83/usr/bin/php artisan queue:work --once --stop-when-empty --tries=1
--   repeated four times.
-- - Queue verification after processing:
--   JOBS=0
--   FAILED_JOBS=0
-- - email_delivery_claims verification:
--   parent_activation:first:1 status=sent
--   child_activation:first:1 status=sent
--   child_activation:first:2 status=sent
--   child_activation:first:3 status=sent
