<?php
// Variables
return [
  "creatorName" => "To Quran",
  "creatorUrl" => "https://toquran.org",
  "templateName" => "To Quran",
  "templateSuffix" => "Learning Dashboard",
  "templateVersion" => "1.0.0",
  "templateFree" => false,
  "templateDescription" => "Private To Quran family and learning dashboard.",
  "templateKeyword" => "To Quran, Quran learning, Arabic, My Deen Journey, family dashboard",
  "licenseUrl" => "",
  "livePreview" => "https://app.toquran.org",
  "productPage" => "https://toquran.org",
  "support" => "mailto:support@toquran.org",
  "moreThemes" => "",
  "ogTitle" => "To Quran",
  "ogImage" => (env('APP_URL') ?: 'https://app.toquran.org') . "/assets/img/logo/logo.png",
  "ogType" => "website",
  "documentation" => "",
  "generator" => "",
  "changelog" => "",
  "repository" => "",
  "gitRepo" => "",
  "gitRepoAccess" => "",
  "githubFreeUrl" => "",
  "facebookUrl" => "",
  "twitterUrl" => "",
  "githubUrl" => "",
  "dribbbleUrl" => "",
  "instagramUrl" => ""
];
